import pygame

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DISPLAYSURF = pygame.display.set_mode((1920, 1080))
TEXT_RECT_START_POINT = (0, 750)
TEXT_RECT_HEIGHT_WIDTH = (1920, 330) #subject to change due to changing DISPLAYSURF parameters
NAME_RECT_START_POINT = (0, 690)
NAME_RECT_HEIGHT_WIDTH = (200, 60)
STORY_TEXT_POINT = (TEXT_RECT_START_POINT[0]+20, TEXT_RECT_START_POINT[1]+20)
NAME_RECT = pygame.Rect(NAME_RECT_START_POINT, NAME_RECT_HEIGHT_WIDTH)
STORY_TEXT_RECT = pygame.Rect(TEXT_RECT_START_POINT, TEXT_RECT_HEIGHT_WIDTH)